<?php
declare(strict_types=1);

// Copy this file to config.php only when configuring manually.
// Running install.php is recommended.

$dbFile = ''; // Required: absolute SQLite database filesystem path generated by the installer.
$username = 'admin';
$passwordHash = 'REPLACE_WITH_A_PASSWORD_HASH';
$installed = true;
$debug = false;
$sessionName = 'sqlite_admin';
